version: 2.1

orbs:
  # Based on https://circleci.com/developer/orbs/orb/circleci/node
  node: circleci/node@5.1.0

jobs:
  test:
    machine:
      # Based on https://circleci.com/docs/using-linuxvm
      image: ubuntu-2204:2022.10.2
      docker_layer_caching: true
    steps:
      - run:
          name: Set auto restart services when upgrading
          # Based on https://www.faqforge.com/linux/fixed-ubuntu-apt-get-upgrade-auto-restart-services
          command: sudo sed -i 's/#$nrconf{restart} = '"'"'i'"'"';/$nrconf{restart} = '"'"'a'"'"';/g' /etc/needrestart/needrestart.conf
      - checkout
      - node/install:
          node-version: '18'
      - run:
          name: Install pnpm
          command: curl -L https://pnpm.js.org/pnpm.js | node - add --global pnpm@7
      - restore_cache:
          name: Restore pnpm cache
          key: pnpm_cache
      - run:
          name: Set up environment
          command: pnpm install && pnpm install-tools && pnpm boot
      - save_cache:
          name: Save pnpm cache
          key: pnpm_cache
          paths:
            - node_modules
      - run:
          name: Run tests
          command: pnpm test
      - store_artifacts:
          path: ./output/test/playwright/html
          destination: playwright-report
      - store_artifacts:
          path: ./output/test/playwright/logs
          destination: playwright-logs
      - store_artifacts:
          path: ./output/test/coverage/report
          destination: coverage-report
      - store_test_results:
          path: ./output/test/playwright/junit.xml
      - run:
          name: Send coverage report to Code Climate
          # Based on https://docs.codeclimate.com/docs/circle-ci-test-coverage-example
          command: |
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
            chmod +x ./cc-test-reporter
            ./cc-test-reporter format-coverage -t lcov -o ./output/test/coverage/report/codeclimate.json ./output/test/coverage/report/lcov.info
            ./cc-test-reporter upload-coverage -i ./output/test/coverage/report/codeclimate.json
      - run:
          name: Audit dependencies
          command: pnpm audit --json

workflows:
  version: 2
  circleci-test:
    jobs:
      - test
